version: "3.1"
  
services:
  pingdirectory:
    image: pingidentity/pingdirectory:latest
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingspdocker/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=baseline/pingdirectory
      - PING_IDENTITY_ACCEPT_EULA=YES
      - PING_IDENTITY_DEVOPS_USER=pingspdocker@gmail.com
      - PING_IDENTITY_DEVOPS_KEY=77a5c082-bebf-4d80-b2b8-6ddff7ab42f6
    ports:
      - 1636:636
      - 1443:443
    networks:
      - pingnet
  pingdataconsole:
    image: pingidentity/pingdataconsole:latest
    ports:
      - 8443:8443
    networks:
      - pingnet


  pingfederate:
    image: pingidentity/pingfederate:latest
    command: wait-for pingdirectory:389 -t 300 -- entrypoint.sh start-server
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingspdocker/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=baseline/pingfederate
      - PING_IDENTITY_ACCEPT_EULA=YES
      - PING_IDENTITY_DEVOPS_USER=pingspdocker@gmail.com
      - PING_IDENTITY_DEVOPS_KEY=77a5c082-bebf-4d80-b2b8-6ddff7ab42f6


    ports:
      - 9031:9031
      - 9999:9999
    networks:
      - pingnet
networks:
    pingnet:
